// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lykfndgzoaxdopxtmfux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5a2ZuZGd6b2F4ZG9weHRtZnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzgwNTMsImV4cCI6MjA2MzcxNDA1M30.hrxtYQKhuzOuT0okyyToSro23rdE-Saco10qBTPfFSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);